# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-apache-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "68:52:54:92:94:27:47:83:a2:40:dd:ca:25:1e:f4:81"

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: Setup tools
          command: |
            sudo apt-get -qq update && sudo apt-get -qqy upgrade
            sudo apt-get -yqq install libpng-dev mariadb-client nano
            sudo docker-php-ext-install gd mbstring mysqli pdo pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - deploy:
          name: deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" = 'master' ]; then
               sudo apt-get install -y rsync
               echo '10people.co.uk,178.62.79.25 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAPZxJCHQLjw0DxW/MI35RHZdj310FqdlkGrZi9fWdPioDzx3wfgvvCkGuqj5iTycM6N7hhw9itmDxuTjoMQvsU=' >> ~/.ssh/known_hosts
               rsync -a ./ 10people.co.uk:~/mckinlays/ && ssh 10people.co.uk rsync -a ~/mckinlays/ /var/www/mckinlays/
            fi
